# Setup
title:            DATA PLAYBOOK
tagline:          'California Health and Human Services Agency'
description:      'CHHS Data Playbook'
url:              'https://gellertnp.github.io/dataplaybook'
baseurl:          'https://gellertnp.github.io/dataplaybook'

markdown:         CommonMarkGhPages

author:
  name:           'California Health and Human Services Agency'
  url:            https://twitter.com/chhsagency

# Custom vars
version:          4.0 | May 2020

github:
  repo:           https://github.com/gellertnp/DataPlaybook

# Google Analytics
google_analytics: UA-56144207-2
